// Package codegen_test asserts that running codegen on the vendored
// spec produces byte-identical output to the committed .gen.go file.
// Drift between generator and committed output is a bug: it means
// either someone edited generated code by hand, or someone bumped the
// spec without re-running `make codegen`.
package codegen_test

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"testing"

	"github.com/e6qu/shimanism/internal/codegen/emit"
	"github.com/e6qu/shimanism/internal/codegen/smithy"
)

// repoRoot resolves to the repo root from the test file's location.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot resolve runtime.Caller")
	}
	// .../internal/codegen/codegen_test.go -> .../..
	return filepath.Join(filepath.Dir(file), "..", "..")
}

func TestCodegen_S3_IsDeterministic(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "services", "storage", "spec", "aws-s3.smithy.json")
	wantPath := filepath.Join(root, "services", "storage", "gen", "aws_s3.gen.go")

	specBytes, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	model, err := smithy.Parse(specBytes)
	if err != nil {
		t.Fatalf("parse spec: %v", err)
	}
	// Look up the upstream commit recorded in SOURCES.md so the test
	// produces the exact bytes that `make codegen` produced last time.
	commit, err := readPinnedCommit(filepath.Join(root, "services", "storage", "spec", "SOURCES.md"))
	if err != nil {
		t.Fatalf("read pinned commit: %v", err)
	}

	// Mirror `make codegen` exactly: every operation declared in the
	// spec, in sorted-by-short-name order.
	allOpIDs := model.AllOperations()
	ops := make([]string, len(allOpIDs))
	for i, id := range allOpIDs {
		ops[i] = smithy.ShortName(id)
	}
	sort.Strings(ops)

	got, err := emit.Emit(model, emit.Options{
		PackageName:  "gen",
		SourceFile:   "services/storage/spec/aws-s3.smithy.json",
		SourceCommit: commit,
		Operations:   ops,
	})
	if err != nil {
		t.Fatalf("emit: %v", err)
	}

	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read committed gen: %v", err)
	}

	if string(got) != string(want) {
		t.Errorf("generated bytes drifted from committed file %s.\nRun `make codegen` and commit the result.", wantPath)
	}
}

func TestCodegen_S3_GeneratesAllOperations(t *testing.T) {
	// The full S3 surface (107 operations at the pinned spec) must
	// generate without errors. Drift in shape kinds or trait coverage
	// surfaces here before it surfaces in CI.
	root := repoRoot(t)
	specBytes, err := os.ReadFile(filepath.Join(root, "services", "storage", "spec", "aws-s3.smithy.json"))
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	model, err := smithy.Parse(specBytes)
	if err != nil {
		t.Fatalf("parse spec: %v", err)
	}
	allOpIDs := model.AllOperations()
	if got, want := len(allOpIDs), 107; got < want {
		// "<" rather than "!=" because upstream may add operations; the
		// determinism test catches drift if it happens.
		t.Errorf("operation count = %d, expected >= %d (the pinned snapshot count)", got, want)
	}
}

// readPinnedCommit pulls the first 40-character hex string between
// backticks out of the SOURCES.md table. Loose grep is fine — the file
// is small and the pinned-commit shape is regular.
func readPinnedCommit(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	s := string(b)
	for i := 0; i < len(s); i++ {
		if s[i] != '`' {
			continue
		}
		// match `<40 hex>`
		end := i + 1 + 40
		if end+1 > len(s) || s[end] != '`' {
			continue
		}
		ok := true
		for _, c := range s[i+1 : end] {
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
				ok = false
				break
			}
		}
		if ok {
			return s[i+1 : end], nil
		}
	}
	return "", os.ErrNotExist
}

