// Package codegen_test asserts that running codegen on the vendored
// spec produces byte-identical output to the committed .gen.go file.
// Drift between generator and committed output is a bug: it means
// either someone edited generated code by hand, or someone bumped the
// spec or the operations manifest without re-running `make codegen`.
package codegen_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/e6qu/shimanism/internal/codegen/emit"
	"github.com/e6qu/shimanism/internal/codegen/smithy"
)

// codegenManifest mirrors services/<svc>/codegen.json. Only the fields
// the test cares about are declared.
type codegenManifest struct {
	Spec       string   `json:"spec"`
	Package    string   `json:"package"`
	Out        string   `json:"out"`
	Operations []string `json:"operations"`
}

// repoRoot resolves to the repo root from the test file's location.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot resolve runtime.Caller")
	}
	return filepath.Join(filepath.Dir(file), "..", "..")
}

func TestCodegen_Storage_IsDeterministic(t *testing.T) {
	root := repoRoot(t)
	manifest := loadManifest(t, filepath.Join(root, "services", "storage", "codegen.json"))

	specBytes, err := os.ReadFile(filepath.Join(root, manifest.Spec))
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	model, err := smithy.Parse(specBytes)
	if err != nil {
		t.Fatalf("parse spec: %v", err)
	}
	commit, err := readPinnedCommit(filepath.Join(root, "services", "storage", "spec", "SOURCES.md"))
	if err != nil {
		t.Fatalf("read pinned commit: %v", err)
	}

	got, err := emit.Emit(model, emit.Options{
		PackageName:  manifest.Package,
		SourceFile:   manifest.Spec,
		SourceCommit: commit,
		Operations:   manifest.Operations,
	})
	if err != nil {
		t.Fatalf("emit: %v", err)
	}

	want, err := os.ReadFile(filepath.Join(root, manifest.Out))
	if err != nil {
		t.Fatalf("read committed gen: %v", err)
	}

	if string(got) != string(want) {
		t.Errorf("generated bytes drifted from committed file %s.\nRun `make codegen` and commit the result.", manifest.Out)
	}
}

func TestCodegen_Storage_ManifestOperationsExist(t *testing.T) {
	// Every operation listed in the manifest must exist in the
	// vendored spec. Typos or operations that AWS later removes are
	// caught here, not at codegen time (codegen would still succeed
	// but the surface would silently shrink).
	root := repoRoot(t)
	manifest := loadManifest(t, filepath.Join(root, "services", "storage", "codegen.json"))

	specBytes, err := os.ReadFile(filepath.Join(root, manifest.Spec))
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	model, err := smithy.Parse(specBytes)
	if err != nil {
		t.Fatalf("parse spec: %v", err)
	}
	for _, op := range manifest.Operations {
		if _, _, err := model.LookupOperation(op); err != nil {
			t.Errorf("manifest operation %q: %v", op, err)
		}
	}
}

func loadManifest(t *testing.T, path string) codegenManifest {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	var m codegenManifest
	if err := json.Unmarshal(b, &m); err != nil {
		t.Fatalf("parse manifest %s: %v", path, err)
	}
	return m
}

// readPinnedCommit pulls the first 40-character hex string between
// backticks out of the SOURCES.md table.
func readPinnedCommit(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	s := string(b)
	for i := 0; i < len(s); i++ {
		if s[i] != '`' {
			continue
		}
		end := i + 1 + 40
		if end+1 > len(s) || s[end] != '`' {
			continue
		}
		ok := true
		for _, c := range s[i+1 : end] {
			if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
				ok = false
				break
			}
		}
		if ok {
			return s[i+1 : end], nil
		}
	}
	return "", os.ErrNotExist
}
