// Command gcp-codegen reads a Google API Discovery JSON document
// and emits Go source describing the service's HTTP routes —
// `(httpMethod, uriPattern, operationID)` triples that downstream
// GCP frontends use to drive their dispatch tables.
//
// Why Discovery → routing only (not types). Per AGENTS.md decision
// #11 (reuse-over-reinvention) the wire-type layer reuses the
// Google Go SDK's REST wire types from `google.golang.org/api/<svc>/v1`
// — same source that this Discovery JSON drives. Re-emitting types
// would duplicate them. The emitter's job is the dispatch layer:
// turn Discovery's URI templates into the regex/ServeMux patterns
// shimanism's GCP frontends already use, so a spec-drift detector
// can compare emitted vs. hand-written routes.
//
// Usage:
//
//	gcp-codegen \
//	  -spec=services/secrets/spec/gcp-secretmanager-discovery.json \
//	  -out=services/secrets/gen/gcp/gcp_secretmanager.gen.go \
//	  -pkg=gcp
//
// Phase 12.B pilot. Single-service driver for now; manifest input
// arrives when the pattern proves out across the remaining 7 GCP
// frontends.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type discoveryDoc struct {
	BaseURL          string                       `json:"baseUrl"`
	DiscoveryVersion string                       `json:"discoveryVersion"`
	Revision         string                       `json:"revision"`
	Resources        map[string]discoveryResource `json:"resources"`
}

type discoveryResource struct {
	Methods   map[string]discoveryMethod   `json:"methods"`
	Resources map[string]discoveryResource `json:"resources"`
}

type discoveryMethod struct {
	ID         string `json:"id"`
	HTTPMethod string `json:"httpMethod"`
	Path       string `json:"path"`
}

// route is a normalised entry the emitter writes.
type route struct {
	ID         string
	HTTPMethod string
	URIPattern string // Discovery URI template, e.g. "v1/{+name}/secrets"
}

func walk(res discoveryResource, out *[]route) {
	for _, m := range res.Methods {
		*out = append(*out, route{
			ID:         m.ID,
			HTTPMethod: m.HTTPMethod,
			URIPattern: m.Path,
		})
	}
	for _, sub := range res.Resources {
		walk(sub, out)
	}
}

func main() {
	var (
		specPath = flag.String("spec", "", "path to the GCP Discovery JSON document")
		outPath  = flag.String("out", "", "path to the generated .gen.go file")
		pkgName  = flag.String("pkg", "gcp", "Go package name for the generated file")
	)
	flag.Parse()
	if *specPath == "" || *outPath == "" {
		flag.Usage()
		fmt.Fprintln(os.Stderr, "\n-spec and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*specPath)
	if err != nil {
		fail("read %s: %v", *specPath, err)
	}
	var doc discoveryDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		fail("parse Discovery JSON: %v", err)
	}

	var routes []route
	for _, r := range doc.Resources {
		walk(r, &routes)
	}
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].HTTPMethod != routes[j].HTTPMethod {
			return routes[i].HTTPMethod < routes[j].HTTPMethod
		}
		if routes[i].URIPattern != routes[j].URIPattern {
			return routes[i].URIPattern < routes[j].URIPattern
		}
		return routes[i].ID < routes[j].ID
	})

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/gcp-codegen from %s.\n", filepath.Base(*specPath))
	fmt.Fprintf(&b, "// Discovery revision: %s.\n", doc.Revision)
	fmt.Fprintf(&b, "// Base URL: %s.\n", doc.BaseURL)
	fmt.Fprintln(&b, "// DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n", *pkgName)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Route is one (httpMethod, uriPattern, operationID) entry from")
	fmt.Fprintln(&b, "// the upstream Google API Discovery document. URIPattern uses")
	fmt.Fprintln(&b, "// Discovery's URI-template syntax verbatim — e.g. `v1/{+name}` —")
	fmt.Fprintln(&b, "// so downstream frontends can compile it to their own dispatch")
	fmt.Fprintln(&b, "// (regex, ServeMux 1.22+ pattern, or otherwise) without losing")
	fmt.Fprintln(&b, "// the original spec semantics.")
	fmt.Fprintln(&b, "type Route struct {")
	fmt.Fprintln(&b, "\tID         string")
	fmt.Fprintln(&b, "\tHTTPMethod string")
	fmt.Fprintln(&b, "\tURIPattern string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Routes is the full operation set the upstream Discovery")
	fmt.Fprintln(&b, "// document declares for this service, sorted by (HTTPMethod,")
	fmt.Fprintln(&b, "// URIPattern) for stable output. Frontends typically intersect")
	fmt.Fprintln(&b, "// this against the cross-cloud operation set documented in")
	fmt.Fprintln(&b, "// per-service OPERATIONS.md.")
	fmt.Fprintln(&b, "var Routes = []Route{")
	for _, r := range routes {
		fmt.Fprintf(&b, "\t{ID: %q, HTTPMethod: %q, URIPattern: %q},\n", r.ID, r.HTTPMethod, r.URIPattern)
	}
	fmt.Fprintln(&b, "}")

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir %s: %v", filepath.Dir(*outPath), err)
	}
	if err := os.WriteFile(*outPath, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", *outPath, err)
	}
	fmt.Printf("wrote %s (%d routes)\n", *outPath, len(routes))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gcp-codegen: "+format+"\n", args...)
	os.Exit(1)
}
