// Command azure-codegen reads an Azure OpenAPI v2 (Swagger) JSON spec,
// converts it to OpenAPI v3 in memory, and runs `oapi-codegen` as a
// library to emit Go types + std-net-http server stubs.
//
// Azure publishes data-plane specs as Swagger 2.0 today
// (https://github.com/Azure/azure-rest-api-specs). oapi-codegen
// consumes only OpenAPI v3, so the conversion step is required
// before generation. `kin-openapi/openapi2conv.ToV3` does that
// conversion canonically — same path the OpenAPI tooling ecosystem
// uses.
//
// Usage:
//
//	azure-codegen \
//	  -spec=services/secrets/spec/azure-keyvault-secrets.json \
//	  -out=services/secrets/gen/azure_keyvault.gen.go \
//	  -pkg=gen
//
// Phase 11.4 pilot. Single-service driver for now (Key Vault
// secrets surface). When the pattern proves out across additional
// Azure services, this command's flags can grow a manifest input
// the way cmd/codegen does.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

func main() {
	var (
		specPath        = flag.String("spec", "", "path to the OpenAPI v2 (Swagger) JSON spec")
		outPath         = flag.String("out", "", "path to the generated .gen.go file")
		pkgName         = flag.String("pkg", "gen", "Go package name for the generated file")
		commit          = flag.String("commit", "", "optional upstream commit SHA to record in the file header")
		commonTypesRoot = flag.String("common-types", "services/common-types", "directory containing vendored Azure common-types/resource-management/v<N>/*.json")
	)
	flag.Parse()
	if *specPath == "" || *outPath == "" {
		flag.Usage()
		fmt.Fprintln(os.Stderr, "\n-spec and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*specPath)
	if err != nil {
		fail("read %s: %v", *specPath, err)
	}

	// Azure ARM specs $ref Azure's shared common-types
	// (common-types/resource-management/v<N>/*.json) by a relative
	// path that mirrors the upstream repo layout. The vendored
	// copies live under services/common-types/. We inline these
	// external references at the v2 layer before converting to v3,
	// so kin-openapi's ToV3 sees a self-contained Swagger doc and
	// emits self-contained v3 parameters / definitions. Doing this
	// at the v2 layer (rather than via openapi3.Loader's external-
	// ref resolution after ToV3) keeps the v2 form of each
	// reusable parameter intact (`type: string` rather than the v3
	// shape `schema: {type: string}`), which the v2→v3 converter
	// then handles correctly.
	if strings.Contains(string(raw), "common-types/") {
		inlined, err := inlineCommonTypes(raw, *commonTypesRoot)
		if err != nil {
			fail("inline common-types: %v", err)
		}
		raw = inlined
	}

	// Parse the v2 spec, convert to v3 in-memory. openapi2conv.ToV3 is
	// the canonical path Azure SDK teams + the OpenAPI ecosystem use
	// to bridge Swagger to v3 generators.
	var v2 openapi2.T
	if err := v2.UnmarshalJSON(raw); err != nil {
		fail("parse v2 spec: %v", err)
	}
	v3, err := openapi2conv.ToV3(&v2)
	if err != nil {
		fail("convert v2 → v3: %v", err)
	}
	// kin-openapi's v2→v3 converter occasionally attaches an empty
	// `AllOf: []` to scalar (enum) schemas. oapi-codegen's MergeSchemas
	// then panics when indexing `allOf[0]` on an empty slice. Walk the
	// converted spec and nil any empty AllOf so generation can proceed.
	normalizeAllOf(v3)

	cfg := codegen.Configuration{
		PackageName: *pkgName,
		Generate: codegen.GenerateOptions{
			Models:        true,
			StdHTTPServer: true,
		},
		OutputOptions: codegen.OutputOptions{
			SkipFmt: false,
		},
	}

	src, err := codegen.Generate(v3, cfg)
	if err != nil {
		fail("oapi-codegen generate: %v", err)
	}

	header := fmt.Sprintf("// Code generated by cmd/azure-codegen from %s.\n", filepath.Base(*specPath))
	if *commit != "" {
		header += fmt.Sprintf("// Upstream commit: %s.\n", *commit)
	}
	header += "// Source spec converted from OpenAPI v2 (Swagger) to v3 via kin-openapi/openapi2conv.ToV3.\n// DO NOT EDIT.\n\n"
	// codegen.Generate emits its own package declaration; replace the
	// header line so our provenance comment sits above the package.
	if idx := strings.Index(src, "package "); idx >= 0 {
		src = header + src[idx:]
	} else {
		src = header + src
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir %s: %v", filepath.Dir(*outPath), err)
	}
	if err := os.WriteFile(*outPath, []byte(src), 0o644); err != nil {
		fail("write %s: %v", *outPath, err)
	}

	fmt.Printf("wrote %s (%d bytes)\n", *outPath, len(src))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "azure-codegen: "+format+"\n", args...)
	os.Exit(1)
}

// commonTypesPattern matches a relative `$ref` into the Azure
// common-types tree (e.g.
// `../../../../../../common-types/resource-management/v4/types.json`)
// so the inliner can decide whether to resolve a $ref against the
// vendored directory.
var commonTypesPattern = regexp.MustCompile(`common-types/resource-management/(v[0-9]+)/([A-Za-z0-9_.-]+)`)

// crossVersionPattern matches the `../v<N>/<file>.json` form used
// by common-types files to reference siblings in a different
// version directory.
var crossVersionPattern = regexp.MustCompile(`\.\./(v[0-9]+)/([A-Za-z0-9_.-]+\.json)`)

// sameVersionPattern matches the `./<file>.json` form used by
// common-types files to reference siblings in the same version
// directory.
var sameVersionPattern = regexp.MustCompile(`^\./([A-Za-z0-9_.-]+\.json)`)

// resolveCommonTypesRef extracts the target (version, file) pair
// from a $ref string in any of the three forms the Azure
// common-types convention uses (full path / same-version sibling /
// cross-version sibling). currentVersion supplies the fallback for
// the same-version shorthand. Returns ok=false if the ref isn't a
// common-types reference.
func resolveCommonTypesRef(ref, currentVersion string) (version, file string, ok bool) {
	if m := commonTypesPattern.FindStringSubmatch(ref); m != nil {
		return m[1], m[2], true
	}
	if m := crossVersionPattern.FindStringSubmatch(ref); m != nil {
		return m[1], m[2], true
	}
	// Drop the URI fragment before matching the same-version form.
	path := ref
	if hi := strings.Index(path, "#"); hi >= 0 {
		path = path[:hi]
	}
	if m := sameVersionPattern.FindStringSubmatch(path); m != nil {
		return currentVersion, m[1], true
	}
	return "", "", false
}

// inlineCommonTypes makes the Swagger doc self-contained by merging
// every common-types file's `definitions` and `parameters` blocks
// into the main doc, then rewriting external `$ref`s to the
// equivalent local pointer. Local refs inside the merged blocks
// stay valid because the common-types names are preserved verbatim
// (no two common-types files in v4 share a definition name today;
// if that ever changes the inliner would need a prefixing scheme).
//
// Two passes:
//  1. Walk the doc, find every external common-types `$ref`, and
//     ensure the target file's `definitions`/`parameters` blocks
//     are merged into the doc (recursive — a common-types file
//     can itself $ref another common-types file).
//  2. Walk the doc again, rewriting each external common-types
//     `$ref` to the local form (`#/definitions/Foo` or
//     `#/parameters/Foo`).
func inlineCommonTypes(raw []byte, root string) ([]byte, error) {
	var doc map[string]interface{}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse spec JSON: %w", err)
	}

	cache := map[string]map[string]interface{}{}
	loadCommon := func(version, file string) (map[string]interface{}, error) {
		key := version + "/" + file
		if d, ok := cache[key]; ok {
			return d, nil
		}
		path := filepath.Join(root, "resource-management", version, file)
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var d map[string]interface{}
		if err := json.Unmarshal(b, &d); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		cache[key] = d
		return d, nil
	}
	ensureMap := func(parent map[string]interface{}, key string) map[string]interface{} {
		if existing, ok := parent[key].(map[string]interface{}); ok {
			return existing
		}
		m := map[string]interface{}{}
		parent[key] = m
		return m
	}
	defs := ensureMap(doc, "definitions")
	params := ensureMap(doc, "parameters")

	// Pass 1: gather every reachable common-types $ref + merge.
	visitedFiles := map[string]bool{}
	var mergeFile func(version, file string) error
	mergeFile = func(version, file string) error {
		key := version + "/" + file
		if visitedFiles[key] {
			return nil
		}
		visitedFiles[key] = true
		common, err := loadCommon(version, file)
		if err != nil {
			return err
		}
		for name, def := range common["definitions"].(map[string]interface{}) {
			if _, exists := defs[name]; !exists {
				defs[name] = def
			}
		}
		if commonParams, ok := common["parameters"].(map[string]interface{}); ok {
			for name, p := range commonParams {
				if _, exists := params[name]; !exists {
					params[name] = p
				}
			}
		}
		// Transitive refs inside the just-merged file. In addition to
		// the full common-types path that appears in main-spec refs,
		// common-types files reference each other via two relative
		// shorthand forms:
		//   - "./<file>.json#/..."         — sibling in same v<N> dir
		//   - "../v<M>/<file>.json#/..."   — cross-version sibling
		// Both resolve against the current file's version.
		var collect func(node interface{}) error
		collect = func(node interface{}) error {
			switch v := node.(type) {
			case map[string]interface{}:
				if refRaw, ok := v["$ref"].(string); ok {
					if tgtVer, tgtFile, ok := resolveCommonTypesRef(refRaw, version); ok {
						if err := mergeFile(tgtVer, tgtFile); err != nil {
							return err
						}
					}
				}
				for _, sub := range v {
					if err := collect(sub); err != nil {
						return err
					}
				}
			case []interface{}:
				for _, sub := range v {
					if err := collect(sub); err != nil {
						return err
					}
				}
			}
			return nil
		}
		return collect(common)
	}
	var collectFromDoc func(node interface{}) error
	collectFromDoc = func(node interface{}) error {
		switch v := node.(type) {
		case map[string]interface{}:
			if refRaw, ok := v["$ref"].(string); ok {
				if m := commonTypesPattern.FindStringSubmatch(refRaw); m != nil {
					if err := mergeFile(m[1], m[2]); err != nil {
						return err
					}
				}
			}
			for _, sub := range v {
				if err := collectFromDoc(sub); err != nil {
					return err
				}
			}
		case []interface{}:
			for _, sub := range v {
				if err := collectFromDoc(sub); err != nil {
					return err
				}
			}
		}
		return nil
	}
	if err := collectFromDoc(doc); err != nil {
		return nil, err
	}

	// Pass 2: rewrite every external $ref (anything with a path
	// component before `#`) to the local pointer that now resolves
	// inside the doc itself. This catches both the main spec's
	// `../../../common-types/v4/types.json#/...` refs and the
	// transitive `../v4/types.json#/...` refs inside merged
	// common-types files.
	var rewrite func(node interface{}) interface{}
	rewrite = func(node interface{}) interface{} {
		switch v := node.(type) {
		case map[string]interface{}:
			if refRaw, ok := v["$ref"].(string); ok {
				hashIdx := strings.Index(refRaw, "#")
				if hashIdx > 0 {
					out := make(map[string]interface{}, len(v))
					for k, sub := range v {
						if k == "$ref" {
							out[k] = "#" + refRaw[hashIdx+1:]
						} else {
							out[k] = rewrite(sub)
						}
					}
					return out
				}
			}
			out := make(map[string]interface{}, len(v))
			for k, sub := range v {
				out[k] = rewrite(sub)
			}
			return out
		case []interface{}:
			out := make([]interface{}, len(v))
			for i, sub := range v {
				out[i] = rewrite(sub)
			}
			return out
		default:
			return v
		}
	}
	return json.Marshal(rewrite(doc))
}

// keep url referenced for future use in the codegen path even when
// the inliner is the active common-types resolver.
var _ = url.Parse

// normalizeAllOf walks every schema in the spec and replaces empty
// AllOf slices with nil. Empty AllOf is semantically a no-op but
// trips oapi-codegen's allOf-aware merge path with an out-of-range
// panic at `allOf[0]`.
func normalizeAllOf(v3 *openapi3.T) {
	visited := map[*openapi3.Schema]bool{}
	var walk func(*openapi3.SchemaRef)
	walk = func(r *openapi3.SchemaRef) {
		if r == nil || r.Value == nil {
			return
		}
		if visited[r.Value] {
			return
		}
		visited[r.Value] = true
		if r.Value.AllOf != nil && len(r.Value.AllOf) == 0 {
			r.Value.AllOf = nil
		}
		for _, sub := range r.Value.AllOf {
			walk(sub)
		}
		for _, sub := range r.Value.AnyOf {
			walk(sub)
		}
		for _, sub := range r.Value.OneOf {
			walk(sub)
		}
		walk(r.Value.Items)
		for _, p := range r.Value.Properties {
			walk(p)
		}
		walk(r.Value.AdditionalProperties.Schema)
	}
	if v3.Components != nil {
		for _, s := range v3.Components.Schemas {
			walk(s)
		}
		for _, p := range v3.Components.Parameters {
			if p.Value != nil {
				walk(p.Value.Schema)
			}
		}
	}
	for _, pi := range v3.Paths.Map() {
		for _, p := range pi.Parameters {
			if p.Value != nil {
				walk(p.Value.Schema)
			}
		}
		for _, op := range pi.Operations() {
			for _, p := range op.Parameters {
				if p.Value != nil {
					walk(p.Value.Schema)
				}
			}
			if op.RequestBody != nil && op.RequestBody.Value != nil {
				for _, mt := range op.RequestBody.Value.Content {
					walk(mt.Schema)
				}
			}
			for _, resp := range op.Responses.Map() {
				if resp.Value == nil {
					continue
				}
				for _, mt := range resp.Value.Content {
					walk(mt.Schema)
				}
				for _, h := range resp.Value.Headers {
					if h.Value != nil {
						walk(h.Value.Schema)
					}
				}
			}
		}
	}
	if v3.Components != nil {
		for _, resp := range v3.Components.Responses {
			if resp.Value == nil {
				continue
			}
			for _, mt := range resp.Value.Content {
				walk(mt.Schema)
			}
			for _, h := range resp.Value.Headers {
				if h.Value != nil {
					walk(h.Value.Schema)
				}
			}
		}
		for _, h := range v3.Components.Headers {
			if h.Value != nil {
				walk(h.Value.Schema)
			}
		}
		for _, rb := range v3.Components.RequestBodies {
			if rb.Value == nil {
				continue
			}
			for _, mt := range rb.Value.Content {
				walk(mt.Schema)
			}
		}
	}
}
