// Command azure-codegen reads an Azure OpenAPI v2 (Swagger) JSON spec,
// converts it to OpenAPI v3 in memory, and runs `oapi-codegen` as a
// library to emit Go types + std-net-http server stubs.
//
// Azure publishes data-plane specs as Swagger 2.0 today
// (https://github.com/Azure/azure-rest-api-specs). oapi-codegen
// consumes only OpenAPI v3, so the conversion step is required
// before generation. `kin-openapi/openapi2conv.ToV3` does that
// conversion canonically — same path the OpenAPI tooling ecosystem
// uses.
//
// Usage:
//
//	azure-codegen \
//	  -spec=services/secrets/spec/azure-keyvault-secrets.json \
//	  -out=services/secrets/gen/azure_keyvault.gen.go \
//	  -pkg=gen
//
// Phase 11.4 pilot. Single-service driver for now (Key Vault
// secrets surface). When the pattern proves out across additional
// Azure services, this command's flags can grow a manifest input
// the way cmd/codegen does.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

func main() {
	var (
		specPath = flag.String("spec", "", "path to the OpenAPI v2 (Swagger) JSON spec")
		outPath  = flag.String("out", "", "path to the generated .gen.go file")
		pkgName  = flag.String("pkg", "gen", "Go package name for the generated file")
		commit   = flag.String("commit", "", "optional upstream commit SHA to record in the file header")
	)
	flag.Parse()
	if *specPath == "" || *outPath == "" {
		flag.Usage()
		fmt.Fprintln(os.Stderr, "\n-spec and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*specPath)
	if err != nil {
		fail("read %s: %v", *specPath, err)
	}

	// Parse the v2 spec, convert to v3 in-memory. openapi2conv.ToV3 is
	// the canonical path Azure SDK teams + the OpenAPI ecosystem use
	// to bridge Swagger to v3 generators.
	var v2 openapi2.T
	if err := v2.UnmarshalJSON(raw); err != nil {
		fail("parse v2 spec: %v", err)
	}
	v3, err := openapi2conv.ToV3(&v2)
	if err != nil {
		fail("convert v2 → v3: %v", err)
	}
	// kin-openapi's v2→v3 converter occasionally attaches an empty
	// `AllOf: []` to scalar (enum) schemas. oapi-codegen's MergeSchemas
	// then panics when indexing `allOf[0]` on an empty slice. Walk the
	// converted spec and nil any empty AllOf so generation can proceed.
	normalizeAllOf(v3)

	cfg := codegen.Configuration{
		PackageName: *pkgName,
		Generate: codegen.GenerateOptions{
			Models:        true,
			StdHTTPServer: true,
		},
		OutputOptions: codegen.OutputOptions{
			SkipFmt: false,
		},
	}

	src, err := codegen.Generate(v3, cfg)
	if err != nil {
		fail("oapi-codegen generate: %v", err)
	}

	header := fmt.Sprintf("// Code generated by cmd/azure-codegen from %s.\n", filepath.Base(*specPath))
	if *commit != "" {
		header += fmt.Sprintf("// Upstream commit: %s.\n", *commit)
	}
	header += "// Source spec converted from OpenAPI v2 (Swagger) to v3 via kin-openapi/openapi2conv.ToV3.\n// DO NOT EDIT.\n\n"
	// codegen.Generate emits its own package declaration; replace the
	// header line so our provenance comment sits above the package.
	if idx := strings.Index(src, "package "); idx >= 0 {
		src = header + src[idx:]
	} else {
		src = header + src
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir %s: %v", filepath.Dir(*outPath), err)
	}
	if err := os.WriteFile(*outPath, []byte(src), 0o644); err != nil {
		fail("write %s: %v", *outPath, err)
	}

	fmt.Printf("wrote %s (%d bytes)\n", *outPath, len(src))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "azure-codegen: "+format+"\n", args...)
	os.Exit(1)
}

// normalizeAllOf walks every schema in the spec and replaces empty
// AllOf slices with nil. Empty AllOf is semantically a no-op but
// trips oapi-codegen's allOf-aware merge path with an out-of-range
// panic at `allOf[0]`.
func normalizeAllOf(v3 *openapi3.T) {
	visited := map[*openapi3.Schema]bool{}
	var walk func(*openapi3.SchemaRef)
	walk = func(r *openapi3.SchemaRef) {
		if r == nil || r.Value == nil {
			return
		}
		if visited[r.Value] {
			return
		}
		visited[r.Value] = true
		if r.Value.AllOf != nil && len(r.Value.AllOf) == 0 {
			r.Value.AllOf = nil
		}
		for _, sub := range r.Value.AllOf {
			walk(sub)
		}
		for _, sub := range r.Value.AnyOf {
			walk(sub)
		}
		for _, sub := range r.Value.OneOf {
			walk(sub)
		}
		walk(r.Value.Items)
		for _, p := range r.Value.Properties {
			walk(p)
		}
		walk(r.Value.AdditionalProperties.Schema)
	}
	if v3.Components != nil {
		for _, s := range v3.Components.Schemas {
			walk(s)
		}
		for _, p := range v3.Components.Parameters {
			if p.Value != nil {
				walk(p.Value.Schema)
			}
		}
	}
	for _, pi := range v3.Paths.Map() {
		for _, op := range pi.Operations() {
			for _, p := range op.Parameters {
				if p.Value != nil {
					walk(p.Value.Schema)
				}
			}
			if op.RequestBody != nil && op.RequestBody.Value != nil {
				for _, mt := range op.RequestBody.Value.Content {
					walk(mt.Schema)
				}
			}
			for _, resp := range op.Responses.Map() {
				if resp.Value == nil {
					continue
				}
				for _, mt := range resp.Value.Content {
					walk(mt.Schema)
				}
			}
		}
	}
}
