// Command azure-codegen reads an Azure OpenAPI v2 (Swagger) JSON spec,
// converts it to OpenAPI v3 in memory, and runs `oapi-codegen` as a
// library to emit Go types + std-net-http server stubs.
//
// Azure publishes data-plane specs as Swagger 2.0 today
// (https://github.com/Azure/azure-rest-api-specs). oapi-codegen
// consumes only OpenAPI v3, so the conversion step is required
// before generation. `kin-openapi/openapi2conv.ToV3` does that
// conversion canonically — same path the OpenAPI tooling ecosystem
// uses.
//
// Usage:
//
//	azure-codegen \
//	  -spec=services/secrets/spec/azure-keyvault-secrets.json \
//	  -out=services/secrets/gen/azure_keyvault.gen.go \
//	  -pkg=gen
//
// Phase 11.4 pilot. Single-service driver for now (Key Vault
// secrets surface). When the pattern proves out across additional
// Azure services, this command's flags can grow a manifest input
// the way cmd/codegen does.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

func main() {
	var (
		specPath        = flag.String("spec", "", "path to the OpenAPI v2 (Swagger) JSON spec")
		outPath         = flag.String("out", "", "path to the generated .gen.go file")
		pkgName         = flag.String("pkg", "gen", "Go package name for the generated file")
		commit          = flag.String("commit", "", "optional upstream commit SHA to record in the file header")
		commonTypesRoot = flag.String("common-types", "services/common-types", "directory containing vendored Azure common-types/resource-management/v<N>/*.json")
	)
	flag.Parse()
	if *specPath == "" || *outPath == "" {
		flag.Usage()
		fmt.Fprintln(os.Stderr, "\n-spec and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*specPath)
	if err != nil {
		fail("read %s: %v", *specPath, err)
	}

	// Azure ARM specs $ref Azure's shared common-types
	// (common-types/resource-management/v<N>/*.json) by a relative
	// path that mirrors the upstream repo layout, and split larger
	// services across sibling spec files in the same directory
	// (e.g. ContainerApps.json $refs ./CommonDefinitions.json). We
	// inline both kinds of external references at the v2 layer
	// before converting to v3, so kin-openapi's ToV3 sees a
	// self-contained Swagger doc and emits self-contained v3
	// parameters / definitions. Doing this at the v2 layer (rather
	// than via openapi3.Loader's external-ref resolution after
	// ToV3) keeps the v2 form of each reusable parameter intact
	// (`type: string` rather than the v3 shape
	// `schema: {type: string}`), which the v2→v3 converter then
	// handles correctly.
	if strings.Contains(string(raw), "common-types/") || strings.Contains(string(raw), `"$ref": "./`) {
		specDir, _ := filepath.Abs(filepath.Dir(*specPath))
		inlined, err := inlineExternalRefs(raw, *commonTypesRoot, specDir)
		if err != nil {
			fail("inline external refs: %v", err)
		}
		raw = inlined
	}

	// Parse the v2 spec, convert to v3 in-memory. openapi2conv.ToV3 is
	// the canonical path Azure SDK teams + the OpenAPI ecosystem use
	// to bridge Swagger to v3 generators.
	var v2 openapi2.T
	if err := v2.UnmarshalJSON(raw); err != nil {
		fail("parse v2 spec: %v", err)
	}
	v3, err := openapi2conv.ToV3(&v2)
	if err != nil {
		fail("convert v2 → v3: %v", err)
	}
	// kin-openapi's v2→v3 converter occasionally attaches an empty
	// `AllOf: []` to scalar (enum) schemas. oapi-codegen's MergeSchemas
	// then panics when indexing `allOf[0]` on an empty slice. Walk the
	// converted spec and nil any empty AllOf so generation can proceed.
	normalizeAllOf(v3)

	cfg := codegen.Configuration{
		PackageName: *pkgName,
		Generate: codegen.GenerateOptions{
			Models:        true,
			StdHTTPServer: true,
		},
		OutputOptions: codegen.OutputOptions{
			SkipFmt: false,
		},
	}

	src, err := codegen.Generate(v3, cfg)
	if err != nil {
		fail("oapi-codegen generate: %v", err)
	}

	header := fmt.Sprintf("// Code generated by cmd/azure-codegen from %s.\n", filepath.Base(*specPath))
	if *commit != "" {
		header += fmt.Sprintf("// Upstream commit: %s.\n", *commit)
	}
	header += "// Source spec converted from OpenAPI v2 (Swagger) to v3 via kin-openapi/openapi2conv.ToV3.\n// DO NOT EDIT.\n\n"
	// codegen.Generate emits its own package declaration; replace the
	// header line so our provenance comment sits above the package.
	if idx := strings.Index(src, "package "); idx >= 0 {
		src = header + src[idx:]
	} else {
		src = header + src
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fail("mkdir %s: %v", filepath.Dir(*outPath), err)
	}
	if err := os.WriteFile(*outPath, []byte(src), 0o644); err != nil {
		fail("write %s: %v", *outPath, err)
	}

	fmt.Printf("wrote %s (%d bytes)\n", *outPath, len(src))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "azure-codegen: "+format+"\n", args...)
	os.Exit(1)
}

// commonTypesPattern matches a relative `$ref` into the Azure
// common-types tree (e.g.
// `../../../../../../common-types/resource-management/v4/types.json`)
// so the inliner can decide whether to resolve a $ref against the
// vendored directory.
var commonTypesPattern = regexp.MustCompile(`common-types/resource-management/(v[0-9]+)/([A-Za-z0-9_.-]+)`)

// crossVersionPattern matches the `../v<N>/<file>.json` form used
// by common-types files to reference siblings in a different
// version directory.
var crossVersionPattern = regexp.MustCompile(`\.\./(v[0-9]+)/([A-Za-z0-9_.-]+\.json)`)

// sameVersionPattern matches the `./<file>.json` form used by
// common-types files to reference siblings in the same version
// directory.
var sameVersionPattern = regexp.MustCompile(`^\./([A-Za-z0-9_.-]+\.json)`)

// refKind is the dispatch category a $ref falls into after parsing.
type refKind int

const (
	refLocal       refKind = iota // local pointer or unrecognised form
	refCommonTypes                // resolves to a common-types/v<N>/<file>.json
	refSibling                    // resolves to a sibling file in the spec dir
)

// classifyRef parses a $ref string and decides how it should be
// resolved. Returns:
//
//   - target file name (basename, or filename within common-types/v<N>/)
//   - common-types version (only meaningful when kind == refCommonTypes)
//   - kind (refLocal / refCommonTypes / refSibling)
//
// `fromCommonTypesVersion` is non-empty when the $ref appears inside
// a common-types file we're merging (the same-version shorthand
// then resolves against that version). `currentDir` is unused for
// classification (the caller passes it to the file loader); it
// stays in the signature so the inliner can extend the classifier
// later without rewiring call sites.
func classifyRef(ref, fromCommonTypesVersion, currentDir string) (target, ctVersion string, kind refKind) {
	_ = currentDir
	if strings.HasPrefix(ref, "#") {
		return "", "", refLocal
	}
	// `./examples/<file>` and `./<other>/<file>` shapes are
	// x-ms-examples metadata — oapi-codegen ignores them and the
	// inliner has no reason to follow them. Skip anything under a
	// subdirectory.
	if strings.HasPrefix(ref, "./examples/") || strings.HasPrefix(ref, "examples/") {
		return "", "", refLocal
	}
	if m := commonTypesPattern.FindStringSubmatch(ref); m != nil {
		return m[2], m[1], refCommonTypes
	}
	if m := crossVersionPattern.FindStringSubmatch(ref); m != nil {
		return m[2], m[1], refCommonTypes
	}
	path := ref
	if hi := strings.Index(path, "#"); hi >= 0 {
		path = path[:hi]
	}
	if m := sameVersionPattern.FindStringSubmatch(path); m != nil {
		file := m[1]
		// "./<file>.json" inside a common-types file → same version
		// in the common-types tree. Inside the main spec → sibling.
		if fromCommonTypesVersion != "" {
			return file, fromCommonTypesVersion, refCommonTypes
		}
		return file, "", refSibling
	}
	return "", "", refLocal
}

// inlineExternalRefs makes the Swagger doc self-contained by merging
// every external file's `definitions` and `parameters` blocks into
// the main doc, then rewriting external `$ref`s to the equivalent
// local pointer. Two external sources are handled:
//
//  1. Azure common-types under
//     `common-types/resource-management/v<N>/<file>.json` — vendored
//     at `commonTypesRoot`. Identified by the path containing
//     `common-types/`.
//  2. Sibling spec files in the same directory as the main spec
//     (e.g. `./CommonDefinitions.json`). Identified by the bare
//     `./<file>.json` prefix when seen from the main doc.
//
// Local refs inside merged blocks stay valid because the source
// names are preserved verbatim. If two source files share a
// definition name the first wins (a deliberate first-write
// semantics; Azure's common-types are namespaced enough that this
// hasn't bitten yet — when it does, the inliner needs a prefixing
// scheme).
//
// Two passes:
//  1. Walk the doc + every merged file's content, find every
//     external `$ref`, and ensure the target file's
//     `definitions`/`parameters` blocks are merged in.
//  2. Walk the doc again, rewriting each external `$ref` to the
//     local form (`#/definitions/Foo` or `#/parameters/Foo`).
func inlineExternalRefs(raw []byte, commonTypesRoot, specDir string) ([]byte, error) {
	var doc map[string]interface{}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse spec JSON: %w", err)
	}

	cache := map[string]map[string]interface{}{}
	loadFile := func(path string) (map[string]interface{}, error) {
		if d, ok := cache[path]; ok {
			return d, nil
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var d map[string]interface{}
		if err := json.Unmarshal(b, &d); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		cache[path] = d
		return d, nil
	}
	commonTypesPath := func(version, file string) string {
		return filepath.Join(commonTypesRoot, "resource-management", version, file)
	}
	siblingPath := func(file string) string {
		return filepath.Join(specDir, file)
	}
	ensureMap := func(parent map[string]interface{}, key string) map[string]interface{} {
		if existing, ok := parent[key].(map[string]interface{}); ok {
			return existing
		}
		m := map[string]interface{}{}
		parent[key] = m
		return m
	}
	defs := ensureMap(doc, "definitions")
	params := ensureMap(doc, "parameters")

	// Pass 1: gather every reachable external $ref + merge. Each
	// merge call is keyed by absolute path to dedupe; the file's
	// definitions + parameters are copied into the main doc, then
	// the file is itself scanned for transitive external refs.
	visitedFiles := map[string]bool{}
	var mergeFile func(path string, fromCommonTypesVersion string) error
	mergeFile = func(path, fromCommonTypesVersion string) error {
		if visitedFiles[path] {
			return nil
		}
		visitedFiles[path] = true
		content, err := loadFile(path)
		if err != nil {
			return err
		}
		// Rewrite every external ref inside the loaded content to its
		// local form BEFORE copying into the doc. Without this step
		// the outer doc walk would re-enter the merged definitions
		// and try to classify their `./<file>.json` shorthand against
		// the spec directory (the wrong context), failing with a
		// file-not-found error.
		rewriteLocal := func(node interface{}) interface{} {
			var walk func(interface{}) interface{}
			walk = func(n interface{}) interface{} {
				switch v := n.(type) {
				case map[string]interface{}:
					if r, ok := v["$ref"].(string); ok {
						if hi := strings.Index(r, "#"); hi > 0 {
							out := make(map[string]interface{}, len(v))
							for k, sub := range v {
								if k == "$ref" {
									out[k] = "#" + r[hi+1:]
								} else {
									out[k] = walk(sub)
								}
							}
							return out
						}
					}
					out := make(map[string]interface{}, len(v))
					for k, sub := range v {
						out[k] = walk(sub)
					}
					return out
				case []interface{}:
					out := make([]interface{}, len(v))
					for i, sub := range v {
						out[i] = walk(sub)
					}
					return out
				default:
					return v
				}
			}
			return walk(node)
		}
		if d, ok := content["definitions"].(map[string]interface{}); ok {
			for name, def := range d {
				if _, exists := defs[name]; !exists {
					defs[name] = rewriteLocal(def)
				}
			}
		}
		if p, ok := content["parameters"].(map[string]interface{}); ok {
			for name, val := range p {
				if _, exists := params[name]; !exists {
					params[name] = rewriteLocal(val)
				}
			}
		}
		// Transitive refs inside the just-merged file. `./<file>.json`
		// resolves against the current file's directory — that's the
		// common-types version directory when fromCommonTypesVersion is
		// set, the spec directory otherwise.
		fileDir := filepath.Dir(path)
		var collect func(node interface{}) error
		collect = func(node interface{}) error {
			switch v := node.(type) {
			case map[string]interface{}:
				if refRaw, ok := v["$ref"].(string); ok {
					if tgt, fromVer, kind := classifyRef(refRaw, fromCommonTypesVersion, fileDir); kind != refLocal {
						switch kind {
						case refCommonTypes:
							if err := mergeFile(commonTypesPath(fromVer, tgt), fromVer); err != nil {
								return err
							}
						case refSibling:
							if err := mergeFile(filepath.Join(fileDir, tgt), ""); err != nil {
								return err
							}
						}
					}
				}
				for _, sub := range v {
					if err := collect(sub); err != nil {
						return err
					}
				}
			case []interface{}:
				for _, sub := range v {
					if err := collect(sub); err != nil {
						return err
					}
				}
			}
			return nil
		}
		return collect(content)
	}
	var collectFromDoc func(node interface{}) error
	collectFromDoc = func(node interface{}) error {
		switch v := node.(type) {
		case map[string]interface{}:
			if refRaw, ok := v["$ref"].(string); ok {
				if tgt, fromVer, kind := classifyRef(refRaw, "", specDir); kind != refLocal {
					switch kind {
					case refCommonTypes:
						if err := mergeFile(commonTypesPath(fromVer, tgt), fromVer); err != nil {
							return err
						}
					case refSibling:
						if err := mergeFile(siblingPath(tgt), ""); err != nil {
							return err
						}
					}
				}
			}
			for _, sub := range v {
				if err := collectFromDoc(sub); err != nil {
					return err
				}
			}
		case []interface{}:
			for _, sub := range v {
				if err := collectFromDoc(sub); err != nil {
					return err
				}
			}
		}
		return nil
	}
	if err := collectFromDoc(doc); err != nil {
		return nil, err
	}

	// Pass 2: rewrite every external $ref (anything with a path
	// component before `#`) to the local pointer that now resolves
	// inside the doc itself. This catches both the main spec's
	// `../../../common-types/v4/types.json#/...` refs and the
	// transitive `../v4/types.json#/...` refs inside merged
	// common-types files.
	var rewrite func(node interface{}) interface{}
	rewrite = func(node interface{}) interface{} {
		switch v := node.(type) {
		case map[string]interface{}:
			if refRaw, ok := v["$ref"].(string); ok {
				hashIdx := strings.Index(refRaw, "#")
				if hashIdx > 0 {
					out := make(map[string]interface{}, len(v))
					for k, sub := range v {
						if k == "$ref" {
							out[k] = "#" + refRaw[hashIdx+1:]
						} else {
							out[k] = rewrite(sub)
						}
					}
					return out
				}
			}
			out := make(map[string]interface{}, len(v))
			for k, sub := range v {
				out[k] = rewrite(sub)
			}
			return out
		case []interface{}:
			out := make([]interface{}, len(v))
			for i, sub := range v {
				out[i] = rewrite(sub)
			}
			return out
		default:
			return v
		}
	}
	return json.Marshal(rewrite(doc))
}

// keep url referenced for future use in the codegen path even when
// the inliner is the active common-types resolver.
var _ = url.Parse

// normalizeAllOf walks every schema in the spec and replaces empty
// AllOf slices with nil. Empty AllOf is semantically a no-op but
// trips oapi-codegen's allOf-aware merge path with an out-of-range
// panic at `allOf[0]`.
func normalizeAllOf(v3 *openapi3.T) {
	visited := map[*openapi3.Schema]bool{}
	var walk func(*openapi3.SchemaRef)
	walk = func(r *openapi3.SchemaRef) {
		if r == nil || r.Value == nil {
			return
		}
		if visited[r.Value] {
			return
		}
		visited[r.Value] = true
		if r.Value.AllOf != nil && len(r.Value.AllOf) == 0 {
			r.Value.AllOf = nil
		}
		for _, sub := range r.Value.AllOf {
			walk(sub)
		}
		for _, sub := range r.Value.AnyOf {
			walk(sub)
		}
		for _, sub := range r.Value.OneOf {
			walk(sub)
		}
		walk(r.Value.Items)
		for _, p := range r.Value.Properties {
			walk(p)
		}
		walk(r.Value.AdditionalProperties.Schema)
	}
	if v3.Components != nil {
		for _, s := range v3.Components.Schemas {
			walk(s)
		}
		for _, p := range v3.Components.Parameters {
			if p.Value != nil {
				walk(p.Value.Schema)
			}
		}
	}
	for _, pi := range v3.Paths.Map() {
		for _, p := range pi.Parameters {
			if p.Value != nil {
				walk(p.Value.Schema)
			}
		}
		for _, op := range pi.Operations() {
			for _, p := range op.Parameters {
				if p.Value != nil {
					walk(p.Value.Schema)
				}
			}
			if op.RequestBody != nil && op.RequestBody.Value != nil {
				for _, mt := range op.RequestBody.Value.Content {
					walk(mt.Schema)
				}
			}
			for _, resp := range op.Responses.Map() {
				if resp.Value == nil {
					continue
				}
				for _, mt := range resp.Value.Content {
					walk(mt.Schema)
				}
				for _, h := range resp.Value.Headers {
					if h.Value != nil {
						walk(h.Value.Schema)
					}
				}
			}
		}
	}
	if v3.Components != nil {
		for _, resp := range v3.Components.Responses {
			if resp.Value == nil {
				continue
			}
			for _, mt := range resp.Value.Content {
				walk(mt.Schema)
			}
			for _, h := range resp.Value.Headers {
				if h.Value != nil {
					walk(h.Value.Schema)
				}
			}
		}
		for _, h := range v3.Components.Headers {
			if h.Value != nil {
				walk(h.Value.Schema)
			}
		}
		for _, rb := range v3.Components.RequestBodies {
			if rb.Value == nil {
				continue
			}
			for _, mt := range rb.Value.Content {
				walk(mt.Schema)
			}
		}
	}
}
